version: '3'
services:
  fastapi:
    build:
      context: ./BackEnd
    ports:
      - "8000:8000"

  blazor:
    build:
      context: ./ClientApp
    ports:
      - "8080:8080"
    depends_on:
      - fastapi
